In [1]:
# Importing the necessary libraries
import numpy as np
import pandas as pd# importing all the important libraries
import re
import numpy as np
import pandas as pd
import string
import nltk
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer , CountVectorizer
import string
import nltk
import re

from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

In [2]:
sw = stopwords.words('english')

In [3]:
# read the positvie text data
pos_rev = pd.read_csv('pos.txt' , sep='\n' , header = None , encoding = 'latin-1')

# adding a tareget column
pos_rev['mood'] = 1.0
pos_rev = pos_rev.rename(columns = {0:'review'})
pos_rev

                                                 review  mood
0     the rock is destined to be the 21st century's ...   1.0
1     the gorgeously elaborate continuation of " the...   1.0
2                        effective but too-tepid biopic   1.0
3     if you sometimes like to go to the movies to h...   1.0
4     emerges as something rare , an issue movie tha...   1.0
...                                                 ...   ...
5326  both exuberantly romantic and serenely melanch...   1.0
5327  mazel tov to a film about a family's joyous li...   1.0
5328  standing in the shadows of motown is the best ...   1.0
5329  it's nice to see piscopo again after all these...   1.0
5330  provides a porthole into that noble , tremblin...   1.0

[5331 rows x 2 columns]

In [4]:
# # Adding target column for pos data
# pos_rev['mood'] = 1.0
# pos_rev = pos_rev.rename(columns = {0:'review'})
# pos_rev

In [5]:
# read the negative text data
neg_rev = pd.read_csv('negative.txt' , sep='\n' , header = None , encoding = 'latin-1')

# adding a tareget column
neg_rev['mood'] = 0.0
neg_rev = neg_rev.rename(columns = {0:'review'})
neg_rev

                                                 review  mood
0                      simplistic , silly and tedious.    0.0
1     it's so laddish and juvenile , only teenage bo...   0.0
2     exploitative and largely devoid of the depth o...   0.0
3     [garbus] discards the potential for pathologic...   0.0
4     a visually flashy but narratively opaque and e...   0.0
...                                                 ...   ...
5326  a terrible movie that some people will neverth...   0.0
5327  there are many definitions of 'time waster' bu...   0.0
5328  as it stands , crocodile hunter has the hurrie...   0.0
5329  the thing looks like a made-for-home-video qui...   0.0
5330  enigma is well-made , but it's just too dry an...   0.0

[5331 rows x 2 columns]

In [6]:
# Cleaning the data

# 1. lower
# 2. remove spaces
# 3. remove punctuation
# 4. remove stopwords
# 5. lemmatize

In [7]:
pos_rev.loc[: , 'review'] = pos_rev.loc[: , 'review'].apply(lambda x : x.lower())
pos_rev.loc[: , 'review'] = pos_rev.loc[: , 'review'].apply(lambda x : re.sub(r"@\S+" , "" , x))
pos_rev.loc[: , 'review'] = pos_rev.loc[: , 'review'].apply\
(lambda x : x.translate(str.maketrans(dict.fromkeys(string.punctuation))))
pos_rev.loc[: , 'review'] = pos_rev.loc[: , 'review'].apply\
(lambda x : " ".join([word for word in x.split() if word not in (sw)]))

In [6]:
neg_rev.loc[: , 'review'] = neg_rev.loc[: , 'review'].apply(lambda x : x.lower())
neg_rev.loc[: , 'review'] = neg_rev.loc[: , 'review'].apply(lambda x : re.sub(r"@\S+" , "" , x))
neg_rev.loc[: , 'review'] = neg_rev.loc[: , 'review'].apply\
(lambda x : x.translate(str.maketrans(dict.fromkeys(string.punctuation))))
neg_rev.loc[: , 'review'] = neg_rev.loc[: , 'review'].apply\
(lambda x : " ".join([word for word in x.split() if word not in (sw)]))

In [7]:
# lemmatization
# pos_rev
from textblob import TextBlob
from textblob import Word

lemmatized_review = []
for i in pos_rev['review']:
    text = TextBlob(i)
    lemmatize=  []
    for j in text.words:
        word = Word(j)
        lemmatize.append(word.lemmatize())
    lemmatized_review.append(" ".join(lemmatize))
pos_rev['lemmatized_review'] = lemmatized_review

In [8]:
lemmatized_review = []
for i in neg_rev['review']:
    text = TextBlob(i)
    lemmatize=  []
    for j in text.words:
        word = Word(j)
        lemmatize.append(word.lemmatize())
    lemmatized_review.append(" ".join(lemmatize))
neg_rev['lemmatized_review'] = lemmatized_review      
neg_rev

,review,mood,lemmatized_review
0,simplistic silly tedious,0.0,simplistic silly tedious
1,laddish juvenile teenage boys could possibly f...,0.0,laddish juvenile teenage boy could possibly fi...
2,exploitative largely devoid depth sophisticati...,0.0,exploitative largely devoid depth sophisticati...
3,garbus discards potential pathological study e...,0.0,garbus discard potential pathological study ex...
4,visually flashy narratively opaque emotionally...,0.0,visually flashy narratively opaque emotionally...
...,...,...,...
5326,terrible movie people nevertheless find moving,0.0,terrible movie people nevertheless find moving
5327,many definitions time waster movie must surely...,0.0,many definition time waster movie must surely one
5328,stands crocodile hunter hurried badly cobbled ...,0.0,stand crocodile hunter hurried badly cobbled l...
5329,thing looks like madeforhomevideo quickie,0.0,thing look like madeforhomevideo quickie
5330,enigma wellmade dry placid,0.0,enigma wellmade dry placid

In [9]:
# Concatenating the pos and neg data

com_rev = pd.concat([pos_rev, neg_rev], axis = 0).reset_index()
com_rev

,index,review,mood,lemmatized_review
0,0,the rock is destined to be the 21st century's ...,1.0,the rock is destined to be the 21st century 's...
1,1,"the gorgeously elaborate continuation of "" the...",1.0,the gorgeously elaborate continuation of the l...
2,2,effective but too-tepid biopic,1.0,effective but too-tepid biopic
3,3,if you sometimes like to go to the movies to h...,1.0,if you sometimes like to go to the movie to ha...
4,4,"emerges as something rare , an issue movie tha...",1.0,emerges a something rare an issue movie that '...
...,...,...,...,...
10657,5326,terrible movie people nevertheless find moving,0.0,terrible movie people nevertheless find moving
10658,5327,many definitions time waster movie must surely...,0.0,many definition time waster movie must surely one
10659,5328,stands crocodile hunter hurried badly cobbled ...,0.0,stand crocodile hunter hurried badly cobbled l...
10660,5329,thing looks like madeforhomevideo quickie,0.0,thing look like madeforhomevideo quickie
10661,5330,enigma wellmade dry placid,0.0,enigma wellmade dry placid

In [10]:
# Train test split
X_train, X_test, y_train, y_test = train_test_split \
(com_rev['lemmatized_review'].values, com_rev['mood'].values, test_size = 0.2, random_state = 101)

In [11]:
# Creating train and test dataframes just to check
train_data = pd.DataFrame({'lemmatized_review': X_train, 'mood': y_train})
test_data = pd.DataFrame({'lemmatized_review': X_test, 'mood': y_test})

In [12]:
train_data

                                      lemmatized_review  mood
0     put washington honest working man john q archi...   0.0
1     poignant if familiar story of a young person s...   1.0
2     more timely than it director could ever have d...   1.0
3                film virtually choke selfconsciousness   0.0
4     a film that take you inside the rhythm of it s...   1.0
...                                                 ...   ...
8524  branagh in his most forceful non-shakespeare s...   1.0
8525  movie friday fan critic damned already like so...   0.0
8526  perhaps heaviest joyless movie ever made giant...   0.0
8527  not a film to rival to live but a fine little ...   1.0
8528  director andrew niccol demonstrates a wry unde...   1.0

[8529 rows x 2 columns]

In [13]:
test_data

                                      lemmatized_review  mood
0     an important movie a reminder of the power of ...   1.0
1     i 've never seen or heard anything quite like ...   1.0
2     the ending doe leave you unfulfilled but these...   1.0
3     on the surface it 's a lovers-on-the-run crime...   1.0
4     walk remember shrewd enough activate girlish t...   0.0
...                                                 ...   ...
2128  bullock doe a good job here of working against...   1.0
2129  the result if not memorable are at least inter...   1.0
2130  apparently designed reverie memory regret thin...   0.0
2131  movie insecure capacity excite churn one two f...   0.0
2132  thrilling provocative and darkly funny this ti...   1.0

[2133 rows x 2 columns]

In [14]:
vectorizer = TfidfVectorizer()
train_vectors = vectorizer.fit_transform(train_data['lemmatized_review'])
test_vectors = vectorizer.transform(test_data['lemmatized_review'])

In [15]:
from sklearn import svm
from sklearn.metrics import classification_report

In [16]:
classifier = svm.SVC(kernel = 'linear')
classifier.fit(train_vectors, train_data['mood'])

SVC(kernel='linear')

In [17]:
pred = classifier.predict(test_vectors)

In [18]:
report = classification_report(test_data['mood'], pred, output_dict = True)
print(f"positive {report['1.0']['recall']}")
print(f"negative {report['0.0']['recall']}")

positive 0.9518518518518518
negative 0.9971509971509972

In [22]:
a = input('write a review: ')

vector = vectorizer.transform([a]).toarray()
xyz = classifier.predict(vector)
print(xyz)

write a review: worst
[0.]

# Using Naive Bayes

In [31]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB, BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()

In [32]:
# Train test split
X_train_NB, X_test_NB, y_train_NB, y_test_NB = train_test_split \
(com_rev['lemmatized_review'].values, com_rev['mood'].values, test_size = 0.3, random_state = 42)

In [33]:
# Creating train and test dataframes just to check
train_data_NB = pd.DataFrame({'lemmatized_review': X_train_NB, 'mood': y_train_NB})
test_data_NB = pd.DataFrame({'lemmatized_review': X_test_NB, 'mood': y_test_NB})

In [34]:
vectorizer = TfidfVectorizer()
train_vectors_NB = vectorizer.fit_transform(train_data_NB['lemmatized_review'])
test_vectors_NB = vectorizer.transform(test_data_NB['lemmatized_review'])
train_vectors_NB.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [35]:
train_data_NB

                                      lemmatized_review  mood
0     comparison earlier film seems disappointingly ...   0.0
1     whats positive thing said new rob schneider ve...   0.0
2     a passionately inquisitive film determined to ...   1.0
3     far more imaginative and ambitious than the tr...   1.0
4                  script judgment sense weight way way   0.0
...                                                 ...   ...
7458  film start promisingly ending predictable far ...   0.0
7459  one of the best of a growing strain of daring ...   1.0
7460  watching chemistry freeman judd however almost...   0.0
7461  an elegant exquisitely modulated psychological...   1.0
7462  character zigzag sufficiently developed suppor...   0.0

[7463 rows x 2 columns]

In [38]:
# Initializing the model
model = MultinomialNB()

# Train the model
model.fit(train_vectors_NB.toarray(), y_train_NB)

MultinomialNB()

In [39]:
# Predict Output 
pred = model.predict(test_vectors_NB.toarray())

In [40]:
# report = classification_report(test_data_NB['mood'], pred, output_dict = True)
# print(f"positive {report['1.0']['precision']}")
# print(f"negative {report['0.0']['precision']}")

In [41]:
report = classification_report(test_data_NB['mood'], pred, output_dict = True)
print(f"positive {report['1.0']['precision']}")
print(f"negative {report['0.0']['precision']}")

positive 0.922722029988466
negative 0.9897610921501706